### ISSUE TITLE
Bug in substring search

### ISSUE THREAD

**Issue by samosafuz** [papyri/navigator#124]
I've noticed an issue when searching for a substring while using `#` to mark word-boundary.

For example, `αυτοθι# THEN #απεσχ` returns no hits (even when a range of some quantity of characters is specified), while `αυτοθι THEN απεσχ` without word-boundary marked returns 97 hits (which is what I expected).

I tested the search by comparing the results for `ετους# THEN #αυτοκρατορ` (1082 hits) and `ετους THEN αυτοκρατορ` (552 hits). In this case, both searches produced results, but the more limited parameters, oddly, produced a _greater_ number, which I found surprising.

I'm not sure what's happening, but something under the hood appears out of order.

**Comment by hcayless** [comment]
This is a tricky one. A decade ago, when the search code was written, Solr had a more expressive but less performant regular expression syntax available, which we used. It permitted regular expressions using word boundary markers (`\b`) which is what we really mean by `#` in searches. This was replaced by a much faster but less expressive regular expression engine (the old one is not available), which does not deal with word boundaries. We fake it by replacing `#` with a space, which works most of the time. 

In proximity searches using characters, however, we run into a problem. Internally, these are turned into regex searches, so `αυτοθι# THEN #απεσχ` becomes `αυτοθι .{1,1} απεσχ`, that is αυτοθι followed by a space, followed by some number of characters between 1 and 1 (1 being the default range if you don't specify a within), followed by a space. In times past, this would have been `αυτοθι\b.{1,1}\bαπεσχ` which would probably have worked, because the single character could have been a space. `ετους# THEN #αυτοκρατορ` works because there are lots of cases of ετους followed by a single digit number followed by αυτοκρατορ. Note that it does **not** pick up the string "ετους αυτοκρατορ" though.

I'd welcome your thoughts on how to deal with this. One possibility is to improve the documentation. You can get what I think you want via a regular expression search, like `REGEX αυτοθι\sαπεσχ`, so we could suggest that. We could just say "don't use # with proximity searches". We could try to rewrite the query for this edge case. Specifically, `αυτοθι .{1,1} απεσχ` probably just means `αυτοθι απεσχ`, but then I'm not 100% sure what `αυτοθι .{1,2} απεσχ` (`αυτοθι# THEN #απεσχ within 2 characters`) would mean. Possibly we could get away with something like `αυτοθι( | .{1,2} )απεσχ`...I may try that out and see what happens.

**Comment by hcayless** [comment]
I was actually able to implement some query rewriting that I think manages to handle this issue appropriately.
