### ISSUE TITLE
Reindex please and gc some repos

### ISSUE THREAD

**Issue by jcowey** [papyri/navigator#166]
There has been a lot going on recently and so I would like to ask you to do a reindex again as soon as you can manage. 

Further more may I ask you to gc on the following repos: 

Translations itself: https://papyri.info/editor/user/board_dashboard?board_id=3

there are a lot of corrupt files on this board. I have managed to rescue some of the stuff from the original user submission. I then winthdraw the file from the Translations board. Voting on this board now takes up to 20 minutes to go through, so I reckon that there is a lot of garbage. I have had huge support from: 

https://papyri.info/editor/users/paulpeters

and, of course, my own board https://papyri.info/editor/users/james.cowey

I hope that if you clean those, the whole voting / make me finalizer etc becomes much smoother and quicker.

**Comment by hcayless** [comment]
Took a while, but Translations repo is now clean.

**Comment by jcowey** [comment]
Is 

https://papyri.info/editor/users/paulpeters

clean? He had reported very slow functions when he engaged with the Translations repo. I suppose that may have been simply because the Translations repo was not clean at the time.

**Comment by hcayless** [comment]
It is. I checked his and yours after cleaning up Translations.

On Aug 31, 2024, at 16:03, James M.S. Cowey ***@***.***> wrote:

﻿

Is

https://papyri.info/editor/users/paulpeters<https://urldefense.com/v3/__https://papyri.info/editor/users/paulpeters__;!!OToaGQ!s6lhTQ3Llu5ZruSARJCqBHh9UDEbfQiEMCLtd6_rE67K2DAyc6P4D_7UB1-ZZD_VwpoWS9nFrxD1Eb5ZHseuzD7XrCxn$>

clean? He had reported very slow functions when he engaged with the Translations repo. I suppose that may have been simply because the Translations repo was not clean at the time.
